In [1]:
import pandas as pd
df=pd.read_csv("https://github.com/HamoyeHQ/HDSC-Introduction-to-Python-for-machine-learning/files/7768140/FoodBalanceSheets_E_Africa_NOFLAG.csv",encoding="latin-1")
df.groupby("Element").sum()# sum of Processing in 2017

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

In [2]:
df.groupby("Item").sum()# sum of Wine produced in 2015 and 2018

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,
"Alcohol, Non-Food",38447,752497,1515090,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,75016,1649136,2171381,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,18060,397035,90990,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,85279,1882494,2567303,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,69280,1352989,1920418,9499.23,10559.15,9853.26,10198.90,9640.51
...,...,...,...,...,...,...,...,...
"Vegetables, Other",77779,1518715,2275409,155038.96,158104.08,156218.90,157752.59,163987.21
Vegetal Products,18060,391905,90990,107145.19,107064.17,106792.72,107655.20,107775.39
Wheat and products,87073,1639683,2654934,232670.13,234710.51,239377.07,240047.62,242645.19
Wine,66206,1319535,1818328,4497.36,4251.81,3872.09,4178.02,4039.32
Yams,50798,970905,1525745,200396.96,203151.78,220626.20,229174.59,221272.09

In [3]:
df.groupby("Area").max()# area with highest sum in 2017

,Area Code,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Area,,,,,,,,,,,
Algeria,4,2961,Yams,5911,Total Population - Both sexes,kg,38924.00,39728.00,40551.00,41389.00,42228.00
Angola,7,2961,Yams,5911,Tourist consumption,kg,26942.00,27884.00,28842.00,29817.00,30810.00
Benin,53,2961,Yams,5911,Total Population - Both sexes,kg,10287.00,10576.00,10872.00,11175.00,11485.00
Botswana,20,2961,Yams,5911,Tourist consumption,kg,2385.00,2383.00,2377.00,2341.00,2342.00
Burkina Faso,233,2961,Yams,5911,Total Population - Both sexes,kg,17586.00,18111.00,18646.00,19193.00,19751.00
Cabo Verde,35,2961,Yams,5911,Tourist consumption,kg,2531.00,2511.00,2522.00,2530.00,2541.00
Cameroon,32,2961,Yams,5911,Total Population - Both sexes,kg,22682.00,23298.00,23927.00,24566.00,25216.00
Central African Republic,37,2961,Yams,5911,Total Population - Both sexes,kg,4464.00,4493.00,4538.00,4596.00,4666.00
Chad,39,2961,Yams,5911,Total Population - Both sexes,kg,13664.00,14111.00,14562.00,15017.00,15478.00
Comoros,45,2782,Pelagic Fish,5911,Production,1000 tonnes,9.29,11.63,17.24,16.65,16.65
Congo,46,2961,Yams,5911,Total Population - Both sexes,kg,4737.00,4856.00,4981.00,5111.00,5244.00
Côte d'Ivoire,107,2961,Yams,5911,Total Population - Both sexes,kg,22648.00,23226.00,23823.00,24437.00,25069.00
Djibouti,72,2961,Yams,5911,Total Population - Both sexes,kg,2581.00,2665.00,2631.00,2664.00,2694.00
Egypt,59,2961,Yams,5911,Tourist consumption,kg,90425.00,92443.00,94447.00,96443.00,98424.00
Eswatini,209,2961,Yams,5911,Total Population - Both sexes,kg,5438.00,5498.00,5511.00,5553.00,5596.00
Ethiopia,238,2961,Yams,5911,Total Population - Both sexes,kg,98094.00,100835.00,103603.00,106400.00,109224.00
Ethiopia PDR,62,2782,Pelagic Fish,5911,Stock Variation,1000 tonnes,0.00,0.00,0.00,0.00,0.00
Gabon,74,2961,Yams,5911,Total Population - Both sexes,kg,2754.00,2749.00,2691.00,2640.00,2633.00
Gambia,75,2960,Yams,5911,Total Population - Both sexes,kg,2593.00,2544.00,2545.00,2544.00,2533.00
Ghana,81,2961,Yams,5911,Total Population - Both sexes,kg,27224.00,27849.00,28482.00,29121.00,30317.00
Guinea,90,2961,Yams,5911,Total Population - Both sexes,kg,11151.00,11432.00,11738.00,12068.00,12414.00
Guinea-Bissau,175,2960,Yams,5911,Total Population - Both sexes,kg,2171.00,2180.00,2201.00,2233.00,2229.00
Kenya,114,2961,Yams,5911,Tourist consumption,kg,46700.00,47878.00,49052.00,50221.00,51393.00
Lesotho,122,2961,Yams,5911,Total Population - Both sexes,kg,2356.00,2193.00,2075.00,2475.00,2323.00
Liberia,123,2961,Yams,5911,Total Population - Both sexes,kg,4360.00,4472.00,4587.00,4702.00,4819.00
Madagascar,129,2961,Yams,5911,Total Population - Both sexes,kg,23590.00,24234.00,24894.00,25571.00,26262.00
Malawi,130,2961,Yams,5911,Total Population - Both sexes,kg,16290.00,16745.00,17205.00,17670.00,18143.00
Mali,133,2961,Yams,5911,Total Population - Both sexes,kg,16934.00,17439.00,17965.00,18512.00,19078.00
Mauritania,136,2961,Yams,5911,Total Population - Both sexes,kg,32373.00,14253.00,21714.00,51864.00,51864.00
Mauritius,137,2961,Wine,5911,Tourist consumption,kg,4044.00,4009.00,3798.00,3713.00,3155.00
Morocco,143,2961,Yams,5911,Total Population - Both sexes,kg,40144.00,53546.00,39247.00,38348.00,38349.00
Mozambique,144,2961,Yams,5911,Total Population - Both sexes,kg,26286.00,27042.00,27830.00,28649.00,29496.00
Namibia,147,2961,Yams,5911,Total Population - Both sexes,kg,2369.00,2427.00,2450.00,2465.00,2469.00
Niger,158,2961,Yams,5911,Total Population - Both sexes,kg,19240.00,20002.00,20789.00,21602.00,22443.00
Nigeria,159,2961,Yams,5911,Total Population - Both sexes,kg,176405.00,181137.00,185960.00,190873.00,195875.00
Rwanda,184,2961,Yams,5911,Total Population - Both sexes,kg,11084.00,11369.00,11669.00,11981.00,12302.00
Sao Tome and Principe,193,2960,Yams,5911,Tourist consumption,kg,2381.00,2369.00,2413.00,2407.00,2446.00
Senegal,195,2961,Yams,5911,Total Population - Both sexes,kg,14175.00,14578.00,14994.00,15419.00,15854.00
Seychelles,196,2782,Pelagic Fish,5911,Stock Variation,1000 tonnes,125.88,160.17,193.57,204.02,204.02
Sierra Leone,197,2961,Wine,5911,Total Population - Both sexes,kg,7017.00,7172.00,7329.00,7488.00,7650.00
South Africa,202,2961,Yams,5911,Total Population - Both sexes,kg,54544.00,55386.00,56208.00,57010.00,57793.00
Sudan,276,2961,Yams,5911,Total Population - Both sexes,kg,37978.00,38903.00,39847.00,40813.00,41802.00
Sudan (former),206,2781,Pelagic Fish,5911,Stock Variation,1000 tonnes,0.00,0.00,0.00,0.00,0.00
Togo,217,2961,Yams,5911,Total Population - Both sexes,kg,7138.00,7323.00,7510.00,7698.00,7889.00
Tunisia,222,2961,Wine,5911,Total Population - Both sexes,kg,11063.00,11180.00,11304.00,11433.00,11565.00
Uganda,226,2961,Yams,5911,Total Population - Both sexes,kg,36912.00,38225.00,39649.00,41167.00,42729.00
United Republic of Tanzania,215,2961,Yams,5911,Total Population - Both sexes,kg,49961.00,51483.00,53049.00,54660.00,56313.00
Zambia,251,2961,Yams,5911,Total Population - Both sexes,kg,15400.00,15879.00,16363.00,16854.00,17352.00
Zimbabwe,181,2961,Wine,5911,Total Population - Both sexes,kg,13587.00,13815.00,14030.00,14237.00,14439.00

In [4]:
df.groupby("Area").min()# 7th lowest sum in 2017

,Area Code,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Area,,,,,,,,,,,
Algeria,4,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-39.0,-19.0,-63.00,-81.0,-90.0
Angola,7,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,0.0,-114.0,-142.00,-250.0,-240.0
Benin,53,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-12.0,-161.0,-46.00,-125.0,-256.0
Botswana,20,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-20.0,-12.0,-25.00,-38.0,-35.0
Burkina Faso,233,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-374.0,-294.0,-53.00,-281.0,-77.0
Cabo Verde,35,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-9.0,-10.0,-13.00,-7.0,-16.0
Cameroon,32,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-49.0,-117.0,-62.00,-147.0,-175.0
Central African Republic,37,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-50.0,-35.0,-2.00,-1.0,-4.0
Chad,39,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-20.0,-121.0,-14.00,-37.0,-10.0
Comoros,45,2761,Cephalopods,5142,Domestic supply quantity,1000 tonnes,0.0,0.0,0.00,0.0,0.0
Congo,46,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-7.0,-2.0,-4.00,-4.0,-17.0
Côte d'Ivoire,107,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-116.0,-208.0,-179.00,-244.0,-151.0
Djibouti,72,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-6.0,-4.0,-7.00,-2.0,-10.0
Egypt,59,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-288.0,-574.0,-985.00,-1582.0,-3396.0
Eswatini,209,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-11.0,-39.0,-51.00,-100.0,-10.0
Ethiopia,238,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-397.0,-549.0,-94.00,-792.0,-1000.0
Ethiopia PDR,62,2761,Crustaceans,5072,Domestic supply quantity,1000 tonnes,0.0,0.0,0.00,0.0,0.0
Gabon,74,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-29.0,-2.0,-18.00,-37.0,-22.0
Gambia,75,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-72.0,-30.0,-16.00,-2.0,-4.0
Ghana,81,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-324.0,-70.0,-162.00,-121.0,-502.0
Guinea,90,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-88.0,-186.0,-84.00,-108.0,-12.0
Guinea-Bissau,175,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-31.0,-6.0,-3.00,-3.0,-3.0
Kenya,114,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-623.0,-250.0,-703.00,-186.0,-177.0
Lesotho,122,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-6.0,-7.0,-5.00,-4.0,-70.0
Liberia,123,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-5.0,-9.0,-2.00,-19.0,-23.0
Madagascar,129,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-300.0,-305.0,-318.00,-324.0,-336.0
Malawi,130,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-344.0,-271.0,-374.00,-50.0,-237.0
Mali,133,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-849.0,-559.0,-560.00,-600.0,-598.0
Mauritania,136,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-7.0,-3.0,-34.00,-1.0,-12.0
Mauritius,137,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-42.0,-47.0,-22.00,-25.0,-34.0
Morocco,143,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-685.0,-179.0,-3225.00,-229.0,-169.0
Mozambique,144,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-219.0,-184.0,-108.00,-1200.0,-1445.0
Namibia,147,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-2.0,-4.0,-38.29,-35.0,-30.0
Niger,158,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-47.0,-57.0,-230.00,-682.0,-434.0
Nigeria,159,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-1796.0,-517.0,-399.00,-694.0,-374.0
Rwanda,184,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-838.0,-827.0,-679.00,-631.0,-682.0
Sao Tome and Principe,193,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-2.0,0.0,0.00,0.0,-1.0
Senegal,195,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-135.0,-33.0,-133.00,-68.0,-101.0
Seychelles,196,2761,"Aquatic Animals, Others",5072,Domestic supply quantity,1000 tonnes,0.0,-1.3,-0.28,0.0,0.0
Sierra Leone,197,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-46.0,-173.0,-240.00,-180.0,-180.0
South Africa,202,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-296.0,-3161.0,-1499.00,-144.0,-597.0
Sudan,276,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-147.0,-1284.0,-58.00,-819.0,-99.0
Sudan (former),206,2761,Aquatic Plants,5072,Domestic supply quantity,1000 tonnes,0.0,0.0,0.00,0.0,0.0
Togo,217,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-27.0,-42.0,-23.00,-32.0,-84.0
Tunisia,222,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-379.0,-154.0,-118.00,-186.0,-319.0
Uganda,226,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-208.0,-131.0,-239.00,-180.0,-271.0
United Republic of Tanzania,215,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-166.0,-317.0,-212.00,-865.0,-913.0
Zambia,251,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-67.0,-907.0,-506.00,-42.0,-529.0
Zimbabwe,181,2501,"Alcohol, Non-Food",511,Domestic supply quantity,1000 persons,-119.0,-369.0,-417.00,-521.0,-273.0

In [5]:
df.corr()# correlation with Element code

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area Code,1.000000,-0.005159,-0.000209,0.006164,0.005472,0.005247,0.005006,0.005665
Item Code,-0.005159,1.000000,-0.024683,0.021722,0.020857,0.020109,0.021494,0.021314
Element Code,-0.000209,-0.024683,1.000000,0.024457,0.023889,0.023444,0.024254,0.024279
Y2014,0.006164,0.021722,0.024457,1.000000,0.994647,0.996081,0.995230,0.994872
Y2015,0.005472,0.020857,0.023889,0.994647,1.000000,0.995739,0.988048,0.988208
Y2016,0.005247,0.020109,0.023444,0.996081,0.995739,1.000000,0.992785,0.992757
Y2017,0.005006,0.021494,0.024254,0.995230,0.988048,0.992785,1.000000,0.998103
Y2018,0.005665,0.021314,0.024279,0.994872,0.988208,0.992757,0.998103,1.000000

In [6]:
df.groupby("Element").max()# highest stock variation

,Area Code,Area,Item Code,Item,Element Code,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,,,,
Domestic supply quantity,276,Zimbabwe,2961,Yams,5301,1000 tonnes,108756.00,110798.00,116483.00,112625.00,117038.00
Export Quantity,276,Zimbabwe,2961,Yams,5911,1000 tonnes,39686.00,52578.00,35420.00,34641.00,34641.00
Fat supply quantity (g/capita/day),276,Zimbabwe,2961,Yams,684,g/capita/day,93.73,96.79,94.33,97.13,94.94
Feed,276,Zimbabwe,2960,Yams,5521,1000 tonnes,29797.00,30472.00,31607.00,29580.00,31567.00
Food,276,Zimbabwe,2961,Yams,5142,1000 tonnes,49014.00,50705.00,52612.00,51220.00,54077.00
Food supply (kcal/capita/day),276,Zimbabwe,2961,Yams,664,kcal/capita/day,3435.00,3454.00,3451.00,3457.00,3450.00
Food supply quantity (kg/capita/yr),276,Zimbabwe,2961,Yams,645,kg,428.27,418.21,419.48,433.38,443.56
Import Quantity,276,Zimbabwe,2961,Yams,5611,1000 tonnes,19582.00,18824.00,19858.00,18627.00,18036.00
Losses,276,Zimbabwe,2949,Yams,5123,1000 tonnes,9807.00,9999.00,10432.00,10342.00,10355.00
Other uses (non-food),276,Zimbabwe,2961,Yams,5154,1000 tonnes,12552.00,6001.00,6099.00,17219.00,17221.00
Processing,276,Zimbabwe,2948,Wine,5131,1000 tonnes,18383.00,21609.00,21739.00,22174.00,22609.00
Production,276,Zimbabwe,2961,Yams,5511,1000 tonnes,109593.00,111663.00,119330.00,117702.00,118172.00
Protein supply quantity (g/capita/day),276,Zimbabwe,2961,Yams,674,g/capita/day,100.34,100.33,100.94,100.10,101.08
Residuals,276,Zimbabwe,2949,Yams,5170,1000 tonnes,16697.00,16136.00,18077.00,17476.00,17323.00
Seed,276,Zimbabwe,2960,Yams,5527,1000 tonnes,1258.00,1352.00,1402.00,1453.00,1474.00
Stock Variation,276,Zimbabwe,2961,Yams,5072,1000 tonnes,4569.00,3418.00,3266.00,5089.00,2226.00
Total Population - Both sexes,276,Zimbabwe,2501,Population,511,1000 persons,176405.00,181137.00,185960.00,190873.00,195875.00
Tourist consumption,193,Sao Tome and Principe,2949,Yams,5171,1000 tonnes,62.00,48.00,6.00,6.00,6.00

In [7]:
df["Area"].nunique()# total number of unique countries in the dataset

49

In [14]:
df["Y2017"].mean()# 2017 mean

140.917764860268

In [15]:
df["Y2017"].std()# 2017 standard deviation

1671.8623590572788

In [16]:
df["Y2014"].isnull().sum()# total number of missing data in 2014

1589